### PR TITLE
[percentile] prevent negative index

### PR DESCRIPTION
**Pull request by andrey-yantsen**
There is an error for too low percentiles.

### CODE REVIEW

**Comment by montanaflynn** [comment]
Thanks for the contribution! Could you add an example to the tests in [percentile_test.go](https://github.com/montanaflynn/stats/blob/master/percentile_test.go)?

**Comment by andrey-yantsen** [comment]
Yep, I've made a force-push with new commit.

**Comment by montanaflynn** [comment]
Great, going to merge the PR now. Thanks again!

**Comment by andrey-yantsen** [comment]
Wow, it was quite fast. Thank you :)

**Pull request merged**
